apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: n8id1i9og-nodejs-gitops
  description: This is GitOps manifest for n8id1i9og-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: n8id1i9og-nodejs
    janus-idp.io/tekton: n8id1i9og-nodejs 
    backstage.io/kubernetes-id: n8id1i9og-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:n8id1i9og-nodejs
